name: auto-merge

on:
  schedule:
    - cron: '*/5 * * * *'   # Every minute
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry-run
        required: false
        default: true
        type: boolean

concurrency:
  group: auto-merge
  cancel-in-progress: false

run-name: >-
  ${{
    format('auto-merge {0}',
      fromJSON('[" (dry-run)", ""]')[github.event.inputs.dry-run != 'true']
    )
  }}

jobs:
  auto-merge-dependabot:
    name: "Dependabot: Enable auto-merge for eligible PRs"
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "DRY_RUN: ${{github.event.inputs.dry-run == 'true'}}"
          exit 0
