name: auto-merge

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry-run
        required: false
        default: true
        type: boolean

concurrency:
  group: auto-merge
  cancel-in-progress: false

jobs:
  auto-merge:
    name: Enable auto-merge for eligible PRs
    runs-on: ubuntu-latest
    env:
      DRY_RUN: ${{ fromJSON('["true", "false"]')[github.event.inputs.dry-run != 'true'] }}

    steps:
      - name: Dry-run
        run: |
          echo "DRY_RUN: ${{ env.DRY_RUN }}"
          exit 0

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Run auto-merge action
        uses: stackrox/actions/automerge@tm/ROX-34007-automerge-configurability
        with:
          github-token: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          # This needs to be overriden for the test to work.
          repository: stackrox/stackrox

  auto-merge-mintmaker:
    name: Enable auto-merge for eligible PRs
    runs-on: ubuntu-latest
    env:
      DRY_RUN: ${{ fromJSON('["true", "false"]')[github.event.inputs.dry-run != 'true'] }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Run auto-merge action
        uses: stackrox/actions/automerge@tm/ROX-34007-automerge-configurability
        with:
          github-token: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          # This needs to be overriden for the test to work.
          repository: stackrox/stackrox
