name: auto-merge

on:
  pull_request_target:
    types:
    - labeled

jobs:
  auto-approve:
    name: Auto-approve Konflux updates
    runs-on: ubuntu-latest
    if: github.actor == 'tommartensen' && github.event.label.name == 'auto-approve' && github.event.pull_request.base.ref == github.event.pull_request.base.repo.default_branch
    steps:
    - env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        echo "I would have run this: "
        echo "gh pr review ${{ github.event.pull_request.number }} \
          --approve --body "Auto-approved by automation." \
          --repo "${{ github.repository }}"

        echo "But GH won't let me do it (as expected)."
