name: Branch
on:
  push:
    branches:
      - master

jobs:
  run-parameters:
    name: Run parameters
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOF >>"$GITHUB_STEP_SUMMARY"
          \`\`\`
          ${{toJSON(github.event.head_commit.url)}}
          \`\`\`
          EOF
          fi
