name: Branch
on:
  push:
    branches:
      - master

jobs:
  run-parameters:
    name: Run parameters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - env:
          COLLECTION_METHOD: core_bpf
        run: |
          echo "Env setting: $COLLECTION_METHOD"
          export COLLECTION_METHOD="KERNEL_MODULE"
          echo "New setting? $COLLECTION_METHOD"
          ${{ github.workspace }}/script.sh
