name: Check PR to release-* branch

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - release-*

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  check-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if fork PR
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "::error::PRs to release branches cannot be forks. Tag @stackrox/release-mgmt on your PR to get help."
          exit 1

      # Only install if cache missed
      - name: Install relacs
        id: install-relacs
        uses: stackrox/actions/release/install-relacs@tm/configurable-install-dir-relacs # ratchet:stackrox/actions/release/install-relacs@v1
        with:
          token: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          version: "v0.0.13+backport-check"

      - name: Check release branch PR
        env:
          GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          # JIRA_USER secret contains the email address of the rhacs-bot user
          JIRA_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          KUBECTL_PLUGIN_KA_HOST: ${{ vars.ACS_KUBECTL_PLUGIN_KA_HOST }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          set -uo pipefail
          echo "# Release branch PR check results" | tee -a "${GITHUB_STEP_SUMMARY}"
          relacs github check-release-pr --pull-request "${PR_URL}" | tee -a "${GITHUB_STEP_SUMMARY}"
