name: Periodically re-run check-release-pr on release-* PRs

on:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rerun:
    name: Re-run check-release-pr on release-* PRs
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-rerun
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Re-run check-release-pr workflows
        env:
          GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
        run: .github/workflows/scripts/rerun-check-release-pr.py
