on:
  workflow_call:
    inputs:
      version:
        description: automation-flavors version
        type: string
        required: true

jobs:
  create-or-update-infra-pr:
    runs-on: ubuntu-latest
    env:
      BRANCH: "bump-automation-flavors-versions-pr-${{ github.event.pull_request.number }}"
    steps:
      - name: Checkout stackrox/infra repository
        uses: actions/checkout@v4
        with:
          repository: stackrox/infra
          token: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          ref: master

      - name: Initialize git and check remote branch exists
        id: check-existing
        run: |
          git config user.name "${{github.event.sender.login}}"
          git config user.email noreply@github.com
          if git ls-remote --quiet --exit-code origin "${BRANCH}"; then
            echo "branch-exists=true" >> "${GITHUB_OUTPUT}"
          else
            echo "branch-exists=false" >> "${GITHUB_OUTPUT}"
          fi

      - name: Create new branch
        if: steps.check-existing.outputs.branch-exists == 'false'
        run: |
          git switch --create "${BRANCH}"

      - name: Switch to branch
        if: steps.check-existing.outputs.branch-exists == 'true'
        run: |
          git fetch origin
          git switch "${BRANCH}"

      - name: Update the automation-flavors version in the infra chart definition
        id: update-automation-flavors-version
        run: |
          yq eval -i '.annotations.automationFlavorsVersion = "${{ inputs.version }}"' chart/infra-server/Chart.yaml
          git add chart/infra-server/Chart.yaml
          if ! git diff-index --quiet HEAD; then
            git commit --message "Bump automation flavors version for ${{ github.event.pull_request.head.sha }}"
            git push --set-upstream --force origin "${BRANCH}"
            echo "Automation flavors version were bumped in infra." >> "$GITHUB_STEP_SUMMARY"
            echo "update-required=true" >> "${GITHUB_OUTPUT}"
          else
            echo "Automation flavors version were not updated in infra, because there is no diff." >> "$GITHUB_STEP_SUMMARY"
            echo "update-required=false" >> "${GITHUB_OUTPUT}"
          fi

      - name: Open Pull Request in stackrox/infra
        if: steps.update-automation-flavors-version.outputs.update-required == 'true'
        id: pull_request
        env:
          GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
        run: |
          if ! gh pr ready; then
            PR_URL=$(gh pr create --repo stackrox/infra \
              --title "chore: Bump version for automation-flavors#${{ github.event.pull_request.number }}" \
              --base "master" \
              --body "Auto-generated: Bump automation-flavors version for https://github.com/stackrox/automation-flavors/pull/${{ github.event.pull_request.number }}." \
              --assignee ${{ github.actor }}
            )
          else
            PR_URL="$(gh pr view --json url --jq .url)"
          fi
          MESSAGE=":arrow_right: A [PR]($PR_URL) has been prepared that will update the used automation flavors with the changes in this PR."
          echo "message=${MESSAGE}" >> "${GITHUB_OUTPUT}"

      - name: Comment on automation-flavors PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          message: ${{ steps.pull_request.outputs.message }}
          comment_tag: infra_pr_link
