name: Milestoner
on:
  pull_request:
    types: [milestoned, demilestoned]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
            echo "Milestone: ${{ github.event.milestone.title }}"
            echo "Milestone Link: ${{ github.event.milestone.html_url }}"
            echo "PR: ${{ github.event.pull_request.html_url }}"
            echo "PR Title: ${{ github.event.pull_request.title }}"
            echo "PR Author: ${{ github.event.pull_request.user.login }}"
