name: Milestoner
on:
  pull_request:
    types: [milestoned, demilestoned]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
            ISSUE_ID="$(echo ${{ github.event.pull_request.title }} | grep --only-matching 'ROX-[0-9]\+' || true)"
            if [ -z "${ISSUE_ID}" ]; then
              echo "no issue id found"
            else
              echo "issue id found"
              curl \
                -sSL \
                --location "https://issues.redhat.com/rest/api/2/issue/${ISSUE_ID}" \
                --header "Authorization: Bearer ${{ secrets.JIRA_TOKEN }}" \
              | jq -r '.key, .fields.summary, .fields.priority.name, .fields.assignee.displayName, .fields.status.name, .fields.issuetype.name'
            fi

      - name: Slack notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: C075SGGM4US
          payload: >-
            {
              "text": "PR <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> (Author: ${{ github.event.pull_request.user.login }}) was added to milestone <${{ github.event.milestone.html_url }}|${{ github.event.milestone.title }}>."
            }
