name: Milestoner
on:
  pull_request:
    types: [milestoned, demilestoned]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Determine context
        id: context
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
            if [ "${{ github.event.action}}" = "milestoned" ]; then
              echo "event-action=added to" >> "${GITHUB_OUTPUT}"
            else
              echo "event-action=removed from" >> "${GITHUB_OUTPUT}"
            fi

            ISSUE_ID="$(echo "${PR_TITLE}" | grep --only-matching 'ROX-[0-9]\+' || true)"
            if [ -n "${ISSUE_ID}" ]; then
              JIRA_INFO=$(curl \
                -sSL \
                --location "https://issues.redhat.com/rest/api/2/issue/${ISSUE_ID}" \
                --header "Authorization: Bearer ${{ secrets.JIRA_TOKEN }}" \
              | jq '{ key: .key, summary: .fields.summary, priority: .fields.priority.name, assignee: .fields.assignee.displayName, status: .fields.status.name, type: .fields.issuetype.name }')
              echo "jira-info=${JIRA_INFO}" >> "${GITHUB_OUTPUT}"
            fi

      - name: Slack notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: C075SGGM4US
          payload: >-
            {
              "text": "PR <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> (Author: ${{ github.event.pull_request.user.login }}) ${{steps.context.outputs.event-action }} milestone <${{ github.event.milestone.html_url }}|${{ github.event.milestone.title }}>."
            }
