name: Check PR to release-* branch

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    branches:
      - release-*

jobs:
  check-release-pr:
    name: "Check release PR status"
    runs-on: ubuntu-latest
    steps:
      - name: Install relacs
        uses: stackrox/actions/release/install-relacs@e57126d0ed98ef43306e38a199f230c3d9afbcfd # ratchet:stackrox/actions/release/install-relacs@v1
        with:
          token: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          version: v0.0.13+backport-check

      - name: Check release PR
        env:
          GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          # JIRA_USER secret contains the email address of the rhacs-bot user
          JIRA_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          KUBECTL_PLUGIN_KA_HOST: ${{ vars.ACS_KUBECTL_PLUGIN_KA_HOST }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          echo "# Release PR check results" | tee -a "${GITHUB_STEP_SUMMARY}"
          relacs github release-pr-check --pull-request "${PR_URL}" | tee -a "${GITHUB_STEP_SUMMARY}"
