name: Render merge windows

on:
  push:
    branches:
      - main
      - tm/render-merge-windows

jobs:
  render-merge-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Install relacs
        env:
          GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
        uses: stackrox/actions/release/install-relacs@v1
        with:
          token: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          # TODO: Remove specific version selector once a new version is released
          version: v0.0.11+merge-windows

      - name: Install oc CLI and KubeArchive kubectl plugin
        run: |
          # Install OC CLI
          curl -sSfLO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz"
          tar -xzf openshift-client-linux.tar.gz
          mv oc /usr/local/bin/

          # Install KubeArchive kubectl plugin
          curl -sSfLO https://github.com/kubearchive/kubearchive/releases/latest/download/kubectl-ka-linux-amd64
          chmod +x kubectl-ka-linux-amd64
          mv kubectl-ka-linux-amd64 /usr/local/bin/kubectl-ka
          kubectl ka version

      - name: Render merge windows
        env:
          GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          KUBECTL_PLUGIN_KA_HOST: ${{ vars.ACS_KUBECTL_PLUGIN_KA_HOST }}
        run: |
          # TODO: use proper SA token, blocked by: https://redhat.atlassian.net/browse/KFLUXSPRT-8705
          oc login --token="${{ secrets.KONFLUX_BOT_0_TOKEN }}" --server=https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443 > /dev/null
          # Split repository name into owner and name
          REPO_OWNER=$(echo ${{ github.repository }} | cut -d '/' -f 1)
          REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          echo "Rendering merge windows for $REPO_OWNER/$REPO_NAME..."
          relacs github list-merge-windows --org $REPO_OWNER --repo $REPO_NAME >> "${GITHUB_STEP_SUMMARY}"
