name: Render merge windows

on:
  push:
    branches:
      - main
      - tm/render-merge-windows

jobs:
  render-merge-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Install relacs
        env:
          GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
        uses: stackrox/actions/release/install-relacs@v1
        with:
          token: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          # TODO: Remove specific version selector once a new version is released
          version: v0.0.11+merge-windows

      - name: Render merge windows
        env:
          GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
          KUBECTL_PLUGIN_KA_HOST: ${{ vars.ACS_KUBECTL_PLUGIN_KA_HOST }}
        run: |
          relacs github list-merge-windows --org ${{ github.repository_owner }} --repo ${{ github.repository }} >> "${GITHUB_STEP_SUMMARY}"
